name: Build GUI (Windows x64)

on:
  pull_request:
    branches:
      - main

jobs:
  build-tageditor-gui-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          .\\venv\\Scripts\\activate
          pip install -r requirements.txt
          pip install PySide6 nuitka zstandard

      - name: Build application for Windows x64
        run: |
          mkdir deploy
          Get-ChildItem -Path . -Exclude deploy,venv | Move-Item -Destination deploy
          cd deploy
          ..\venv\Scripts\activate
          echo "yes" | pyside6-deploy -c src/build/pysidedeploy_windows.spec main.py

      - name: Archive Windows x64 build
        uses: actions/upload-artifact@v4
        with:
          name: pyside6-application-windows-x64
          path: deploy/main.exe
          asset_path: ./artifacts/main.exe
          asset_name: TagEditor_GUI_Windows_x64.exe
          asset_content_type: application/octet-stream
